# LifeSaver Hospital Management System
database.url=jdbc:sqlserver://DESKTOP-SIE694J\\MEME;databaseName=LifeSaverHospitalDatabase;encrypt=false;trustServerCertificate=true
database.username=lifesaver_app
database.password=LifeSaverDb@12345
